# Using postgresql for development
development:
  adapter: postgresql
  database: sitm_db
  pool: 5
  timeout: 5000

# Using postgresql for test
test:
  adapter: postgresql
  database: sitm_db_test
  pool: 5
  timeout: 5000
